version: "2"

services:
    app-server:
        image: shito/alpine-nginx-php7:edge
        ports:
            - 80:80
            - 443:443
        volumes:
            - /Users/donbstringham/Sandbox/wsu-cs3620/final/src/public:/usr/share/nginx/html
            - /Users/donbstringham/Sandbox/wsu-cs3620/final/src:/usr/share/nginx
        links:
            - mysql:mysql
            - redis:redis
        depends_on:
            - mysql
            - redis

    mysql:
        image: shito/alpine-mariadb:edge
        ports:
            - 3306:3306
        volumes:
            - /Users/donbstringham/Sandbox/wsu-cs3620/data/mysql:/data
        environment:
            - MYSQL_ROOT_PASSWORD=changeme
            - MYSQL_DATABASE=cs3620
            - MYSQL_USER=foo
            - MYSQL_PASSWORD=bar

    redis:
        image: shito/alpine-redis:edge
        ports:
            - 6379:6379
        volumes:
            - /Users/donbstringham/Sandbox/wsu-cs3620/data/redis:/data
            
